[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "functions"

[functions."ng-heartbeat"]
  schedule = "*/20 * * * *"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
